//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amazon.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string lblAboutUs {
            get {
                return ResourceManager.GetString("lblAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string lblAboutUsPage {
            get {
                return ResourceManager.GetString("lblAboutUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string lblAddToCart {
            get {
                return ResourceManager.GetString("lblAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Favourite.
        /// </summary>
        internal static string lblAddToFavourite {
            get {
                return ResourceManager.GetString("lblAddToFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Products.
        /// </summary>
        internal static string lblAllProducts {
            get {
                return ResourceManager.GetString("lblAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Products.
        /// </summary>
        internal static string lblAppleProducts {
            get {
                return ResourceManager.GetString("lblAppleProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string lblArabic {
            get {
                return ResourceManager.GetString("lblArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string lblBuyNow {
            get {
                return ResourceManager.GetString("lblBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Page.
        /// </summary>
        internal static string lblCartPage {
            get {
                return ResourceManager.GetString("lblCartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cart Products.
        /// </summary>
        internal static string lblCartProducts {
            get {
                return ResourceManager.GetString("lblCartProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string lblDarkTheme {
            get {
                return ResourceManager.GetString("lblDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discout Phones.
        /// </summary>
        internal static string lblDiscoutPhones {
            get {
                return ResourceManager.GetString("lblDiscoutPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics Products.
        /// </summary>
        internal static string lblElectronicsProducts {
            get {
                return ResourceManager.GetString("lblElectronicsProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Cart Please Add Items in Cart.
        /// </summary>
        internal static string lblEmptyCart {
            get {
                return ResourceManager.GetString("lblEmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Favourite Please Add Items in Favourite.
        /// </summary>
        internal static string lblEmptyFavourite {
            get {
                return ResourceManager.GetString("lblEmptyFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        internal static string lblEnterFirstName {
            get {
                return ResourceManager.GetString("lblEnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        internal static string lblEnterLastName {
            get {
                return ResourceManager.GetString("lblEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Confirm Password.
        /// </summary>
        internal static string lblEnterYourConfirmPassword {
            get {
                return ResourceManager.GetString("lblEnterYourConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        internal static string lblEnterYourEmail {
            get {
                return ResourceManager.GetString("lblEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password.
        /// </summary>
        internal static string lblEnterYourPassword {
            get {
                return ResourceManager.GetString("lblEnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Items.
        /// </summary>
        internal static string lblFavouriteItems {
            get {
                return ResourceManager.GetString("lblFavouriteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Page.
        /// </summary>
        internal static string lblFavouritePage {
            get {
                return ResourceManager.GetString("lblFavouritePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Favourite Products.
        /// </summary>
        internal static string lblFavouriteProducts {
            get {
                return ResourceManager.GetString("lblFavouriteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Detials Page.
        /// </summary>
        internal static string lblItemDetialsPage {
            get {
                return ResourceManager.GetString("lblItemDetialsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items List Page.
        /// </summary>
        internal static string lblItemListPage {
            get {
                return ResourceManager.GetString("lblItemListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languague.
        /// </summary>
        internal static string lblLanguague {
            get {
                return ResourceManager.GetString("lblLanguague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string lblLightTheme {
            get {
                return ResourceManager.GetString("lblLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show New Products.
        /// </summary>
        internal static string lblNewProducts {
            get {
                return ResourceManager.GetString("lblNewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        internal static string lblNewProducts2 {
            get {
                return ResourceManager.GetString("lblNewProducts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an Account?.
        /// </summary>
        internal static string lblNotHaveAccount {
            get {
                return ResourceManager.GetString("lblNotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Popular Products.
        /// </summary>
        internal static string lblPopularProducts {
            get {
                return ResourceManager.GetString("lblPopularProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        internal static string lblPopularProducts2 {
            get {
                return ResourceManager.GetString("lblPopularProducts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Descreption.
        /// </summary>
        internal static string lblProductDescreption {
            get {
                return ResourceManager.GetString("lblProductDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Items.
        /// </summary>
        internal static string lblRelatedItems {
            get {
                return ResourceManager.GetString("lblRelatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string lblRemove {
            get {
                return ResourceManager.GetString("lblRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung Products.
        /// </summary>
        internal static string lblSamsungProducts {
            get {
                return ResourceManager.GetString("lblSamsungProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Later.
        /// </summary>
        internal static string lblSaveLater {
            get {
                return ResourceManager.GetString("lblSaveLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Items.
        /// </summary>
        internal static string lblSearchPage {
            get {
                return ResourceManager.GetString("lblSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string lblSettingsPage {
            get {
                return ResourceManager.GetString("lblSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Phones.
        /// </summary>
        internal static string lblShowAllPhones {
            get {
                return ResourceManager.GetString("lblShowAllPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string lblShowAllProducts {
            get {
                return ResourceManager.GetString("lblShowAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblSignIn {
            get {
                return ResourceManager.GetString("lblSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string lblSignOut {
            get {
                return ResourceManager.GetString("lblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree With Conditions And Terms.
        /// </summary>
        internal static string lblTerms {
            get {
                return ResourceManager.GetString("lblTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Price is.
        /// </summary>
        internal static string lblTotalPrice {
            get {
                return ResourceManager.GetString("lblTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Settings.
        /// </summary>
        internal static string lblViewSettings {
            get {
                return ResourceManager.GetString("lblViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaomi Products.
        /// </summary>
        internal static string lblXiaomiProducts {
            get {
                return ResourceManager.GetString("lblXiaomiProducts", resourceCulture);
            }
        }
    }
}
